name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "PATH=$HOME/.koyeb/bin:$PATH" >> $GITHUB_ENV

      - name: Deploy to Koyeb
        run: |
          koyeb service update eshop \
          --app fit-liuka \
          --token ${{ secrets.KOYEB_API_TOKEN }}