name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Koyeb CLI
        run: |
          curl -LO https://github.com/koyeb/koyeb-cli/releases/latest/download/koyeb_linux_amd64.tar.gz
          tar -xvf koyeb_linux_amd64.tar.gz
          sudo mv koyeb /usr/local/bin
      - run: koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
      - run: npm run build
      - run: koyeb deploy
