jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "PATH=$HOME/.koyeb/bin:$PATH" >> $GITHUB_ENV

      - name: Create Koyeb config file
        run: |
          mkdir -p $HOME/.koyeb
          echo "token: ${{ secrets.KOYEB_API_TOKEN }}" > $HOME/.koyeb.yaml

      - name: Deploy to Koyeb
        run: koyeb deploy --app my-app