name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g koyeb
      - run: koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
      - run: npm run build
      - run: koyeb deploy
