name: PMD Code Analysis

on:
  push:
    branches:
      - '**'  # triggers on push events to every branch

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Run PMD analysis and generate SARIF report
        uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '7.0.0-rc4'
          rulesets: 'ruleset.xml'
          analyzeModifiedFilesOnly: false
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != '0'
        run: exit 1
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
